export type ReviewScope = "working" | "staged" | "branch";
export type ReviewFile = { path: string; status: string; additions: number | null; deletions: number | null };
export type GitReview = {
  root: string;
  branch: string;
  bases: string[];
  base: string | null;
  comparison: string;
  files: ReviewFile[];
  patch?: string;
  truncated?: boolean;
  head?: string | null;
  upstream?: string | null;
  remotes?: string[];
  ahead?: number | null;
  behind?: number | null;
  stagedFiles?: string[];
  conflictedFiles?: string[];
  preview?: { content: string | null; revision: string; truncated: boolean; reason?: string };
};
export type GitReviewRequest = { workingDir: string; restrictRoot: boolean; scope: ReviewScope; base?: string; file?: string };
